name: Delete All GitHub Pages Deployments (with inactive status)

on:
  workflow_dispatch:

jobs:
  delete-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all github-pages deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          deployments=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/deployments?environment=github-pages" | jq '.[].id')

          if [ -z "$deployments" ]; then
            echo "No deployments found."
            exit 0
          fi

          for id in $deployments; do
            echo "Setting deployment $id to inactive..."
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -d '{"state":"inactive"}' \
              "https://api.github.com/repos/$REPO/deployments/$id/statuses"

            echo "Deleting deployment $id ..."
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO/deployments/$id"
          done
