name: Delete All GitHub Pages Deployments (force status update)

on:
  workflow_dispatch:

jobs:
  delete-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch deployments for github-pages environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          deployments=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/deployments?environment=github-pages" | jq -r '.[].id')

          if [ -z "$deployments" ]; then
            echo "No deployments found."
            exit 0
          fi

          for id in $deployments; do
            echo "Setting deployment $id to inactive..."
            status=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -d '{"state":"inactive"}' \
              "https://api.github.com/repos/$REPO/deployments/$id/statuses" | jq -r '.state')

            if [ "$status" == "inactive" ]; then
              echo "Deleting deployment $id ..."
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO/deployments/$id"
            else
              echo "Failed to set deployment $id to inactive."
            fi
          done
